# SPDX-FileCopyrightText: 2023 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

stages:
  - build
  - lint
  - test
  - deploy

image: golang:1.22

build:
  stage: build
  parallel:
    matrix:
      - GOOS: ["linux", "windows"]
  before_script:
    - .ci/setup-build.sh
  script:
    - just build
  artifacts:
    expire_in: 1 day
    paths:
      - dist

test:
  stage: test
  needs: []
  script:
    - make test

test-postgres:
  stage: test
  services:
    - postgres:15
  needs: []
  variables:
    CGO_ENABLED: 1

    # see https://docs.gitlab.com/ee/ci/services/postgres.html
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: wfx
    POSTGRES_USER: wfx
    POSTGRES_PASSWORD: secret
    POSTGRES_HOST_AUTH_METHOD: trust

    PGHOST: postgres
    PGPORT: 5432
    PGDATABASE: $POSTGRES_DB
    PGUSER: $POSTGRES_USER
    PGPASSWORD: $POSTGRES_PASSWORD
    PGSSLMODE: disable
  before_script:
    - .ci/setup-postgres.sh
  script:
    - just postgres-integration-test

test-mysql:
  stage: test
  services:
    - mysql:8-debian
  needs: []
  variables:
    CGO_ENABLED: 1

    # see https://docs.gitlab.com/ee/ci/services/mysql.html
    # Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: wfx
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: wfx
    MYSQL_PASSWORD: secret
    MYSQL_HOST: mysql
  before_script:
    - .ci/setup-mysql.sh
  script:
    - just mysql-integration-test

cli-tests:
  stage: test
  needs: []
  services:
    - postgres:15
    - mysql:8-debian
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CGO_ENABLED: 1

    # see https://docs.gitlab.com/ee/ci/services/mysql.html
    # Configure mysql service (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: wfx
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: wfx
    MYSQL_PASSWORD: secret
    MYSQL_HOST: mysql

    # see https://docs.gitlab.com/ee/ci/services/postgres.html
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
    POSTGRES_DB: wfx
    POSTGRES_USER: wfx
    POSTGRES_PASSWORD: secret
    POSTGRES_HOST_AUTH_METHOD: trust

    PGHOST: postgres
    PGPORT: 5432
    PGUSER: wfx
    PGPASSWORD: secret
    PGDATABASE: wfx
  before_script:
    - .ci/setup-cli-tests.sh
    - make
    - make install
  script:
    - cd test && bats .

lint:
  stage: lint
  needs: []
  before_script:
    - .ci/setup-lint.sh
  script:
    - just lint

reuse:
  stage: lint
  needs: []
  image:
    name: fsfe/reuse:latest
    entrypoint: [""] # default entrypoint is "reuse" which doesn't work for CI
  script:
    - reuse lint || true # just a warning

generate:
  stage: lint
  needs: []
  before_script:
    - .ci/setup-generate.sh
    - git lfs install && git submodule update
  script:
    - just generate
    - git diff --exit-code
