# SPDX-FileCopyrightText: 2023 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
name: Pages
on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  pages:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Disable git security features
        run: git config --global safe.directory '*'
      - run: .ci/setup-pages.sh
      # check for broken links
      - run: just check-md-links
      - run: cd hugo && npm ci
      - run: just pages
        env:
          HUGO_BASEURL: ${{ vars.HUGO_BASEURL }}
      - run: ls -al public/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
