# SPDX-FileCopyrightText: 2023 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  wfx:
    runs-on: ubuntu-latest
    container: golang:1.22.4@sha256:3589439790974ec05491b66b656bf1048d0f50dd010a903463e3156ba1fc26de
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: Disable git security features
        run: git config --global safe.directory '*'
      - run: .ci/setup-build.sh
      # goreleaser requires an absolute path to the compiler
      - run: install -m0755 .ci/zcc /usr/local/bin/zcc
      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGE_DEPLOY_USER }}
          password: ${{ secrets.PACKAGE_DEPLOY_TOKEN }}
      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_DEPLOY_TOKEN }}
          CC: /usr/local/bin/zcc
