# SPDX-FileCopyrightText: 2023 Siemens AG
#
# SPDX-License-Identifier: Apache-2.0
#
# Author: Michael Adler <michael.adler@siemens.com>
---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  wfx:
    runs-on: ubuntu-latest
    container: golang:1.22.3@sha256:f43c6f049f04cbbaeb28f0aad3eea15274a7d0a7899a617d0037aec48d7ab010
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Disable git security features
        run: git config --global safe.directory '*'
      - run: .ci/setup-build.sh
      # goreleaser requires an absolute path to the compiler
      - run: install -m0755 .ci/zcc /usr/local/bin/zcc
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGE_DEPLOY_USER }}
          password: ${{ secrets.PACKAGE_DEPLOY_TOKEN }}
      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_DEPLOY_TOKEN }}
          CC: /usr/local/bin/zcc
